"use client";

import { useCallback, useEffect, useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { archiveDraftAction, deleteDraftAction, generateDraftAction, restoreDraftAction, updateDraftAction } from "./actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

export function DraftEditor({
  draft,
  autoGenerate,
  isArchived = false,
  canDelete = false,
}: {
  draft: any;
  autoGenerate?: boolean;
  isArchived?: boolean;
  canDelete?: boolean;
}) {
  const router = useRouter();
  const [title, setTitle] = useState(draft.title || "");
  const [subject, setSubject] = useState(draft.subject || "");
  const [body, setBody] = useState(draft.body || "");
  const [archived, setArchived] = useState(Boolean(isArchived));
  const [isSaving, startSaving] = useTransition();
  const [isGenerating, startGenerating] = useTransition();
  const [isArchiving, startArchiving] = useTransition();
  const [isDeleting, startDeleting] = useTransition();
  const autoGeneratedRef = useRef(false);
  const generationRequestedRef = useRef(false);
  const lastUpdatedAtRef = useRef(draft.updated_at || "");

  const hasContent = Boolean(subject || body);

  const runGeneration = useCallback(() => {
    generationRequestedRef.current = true;
    startGenerating(async () => {
      try {
        await generateDraftAction(draft.id);
        toast.success("Draft generation started in background.", {
          description: "We will notify you when it is ready.",
        });
      } catch (e: any) {
        generationRequestedRef.current = false;
        toast.error(e?.message || "Failed to generate draft");
      }
    });
  }, [draft.id, startGenerating]);

  const runArchive = useCallback(() => {
    startArchiving(async () => {
      try {
        await archiveDraftAction(draft.id);
        setArchived(true);
        toast.success("Draft archived");
        router.refresh();
      } catch (e: any) {
        toast.error(e?.message || "Failed to archive draft");
      }
    });
  }, [draft.id, router, startArchiving]);

  const runRestore = useCallback(() => {
    startArchiving(async () => {
      try {
        await restoreDraftAction(draft.id);
        setArchived(false);
        toast.success("Draft restored");
        router.refresh();
      } catch (e: any) {
        toast.error(e?.message || "Failed to restore draft");
      }
    });
  }, [draft.id, router, startArchiving]);

  const runDelete = useCallback(() => {
    if (!confirm("Delete this draft? This cannot be undone.")) return;
    startDeleting(async () => {
      try {
        await deleteDraftAction(draft.id);
        toast.success("Draft deleted");
        router.push("/app/comms");
        router.refresh();
      } catch (e: any) {
        toast.error(e?.message || "Failed to delete draft");
      }
    });
  }, [draft.id, router, startDeleting]);

  useEffect(() => {
    if (!autoGenerate || autoGeneratedRef.current || hasContent) return;
    autoGeneratedRef.current = true;
    runGeneration();
  }, [autoGenerate, hasContent, runGeneration]);

  useEffect(() => {
    const updatedAt = draft.updated_at || "";
    if (!updatedAt || updatedAt === lastUpdatedAtRef.current) return;
    lastUpdatedAtRef.current = updatedAt;
    if (!generationRequestedRef.current) return;
    generationRequestedRef.current = false;
    setTitle(draft.title || "");
    setSubject(draft.subject || "");
    setBody(draft.body || "");
  }, [draft.body, draft.subject, draft.title, draft.updated_at]);

  useEffect(() => {
    setArchived(Boolean(isArchived));
  }, [isArchived]);

  return (
    <form
      action={(fd) => {
        startSaving(async () => {
          try {
            await updateDraftAction(fd);
            toast.success("Saved");
          } catch (e: any) {
            toast.error(e?.message || "Failed to save");
          }
        });
      }}
      className="space-y-4"
    >
      <input type="hidden" name="id" value={draft.id} />

      {archived ? (
        <div className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-900">
          This draft is archived. Restore it to keep working on it.
        </div>
      ) : null}

      <div className="space-y-2">
        <label className="text-sm font-medium">Title</label>
        <Input name="title" value={title} onChange={(e) => setTitle(e.target.value)} required />
      </div>

      <div className="space-y-2">
        <label className="text-sm font-medium">Subject (if email/newsletter)</label>
        <Input name="subject" value={subject} onChange={(e) => setSubject(e.target.value)} />
      </div>

      <div className="space-y-2">
        <label className="text-sm font-medium">Body</label>
        <Textarea name="body" value={body} onChange={(e) => setBody(e.target.value)} rows={18} />
      </div>

      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex flex-wrap items-center gap-2">
          <Button type="button" variant="secondary" onClick={runGeneration} disabled={isGenerating}>
          {isGenerating ? "Generating…" : hasContent ? "Regenerate draft" : "Generate draft"}
          </Button>
          <Button
            type="button"
            variant="secondary"
            onClick={archived ? runRestore : runArchive}
            disabled={isArchiving}
          >
            {isArchiving ? "Working…" : archived ? "Restore" : "Archive"}
          </Button>
          {canDelete ? (
            <Button type="button" variant="ghost" onClick={runDelete} disabled={isDeleting}>
              {isDeleting ? "Deleting…" : "Delete"}
            </Button>
          ) : null}
        </div>
        <Button type="submit" disabled={isSaving}>
          {isSaving ? "Saving…" : "Save"}
        </Button>
      </div>
    </form>
  );
}
